services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: banking_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d banking_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - banking-network

  liquibase:
    image: liquibase/liquibase:latest
    container_name: liquibase-migration
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
    command: >
      --url="jdbc:postgresql://postgres:5432/banking_db"
      --username=user
      --password=password
      --changeLogFile=db.changelog-master.xml
      --searchPath=/liquibase/changelog
      update
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - banking-network

volumes:
  postgres_data:

networks:
  banking-network:
    driver: bridge
