apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/hungdq/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sat, 27 Sep 2025 05:05:39 +07
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: cluster_info
    server: https://127.0.0.1:52656
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/hungdq/.minikube/profiles/minikube/client.crt
    client-key: /Users/hungdq/.minikube/profiles/minikube/client.key
