apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-bank-config
  namespace: simple-bank
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/banking_db"
  SPRING_DATASOURCE_USERNAME: "user"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  # Enable Liquibase for database migrations
  SPRING_LIQUIBASE_ENABLED: "true"
  SPRING_LIQUIBASE_CHANGE_LOG: "classpath:db/changelog/db.changelog-master.xml"
