apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-app
  namespace: simple-bank
  labels:
    app: simple-bank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-bank
  template:
    metadata:
      labels:
        app: simple-bank
    spec:
      initContainers:
      - name: liquibase-migration
        image: liquibase/liquibase:latest
        env:
        - name: LIQUIBASE_URL
          value: "jdbc:postgresql://postgres-service:5432/banking_db"
        - name: LIQUIBASE_USERNAME
          value: "user"
        - name: LIQUIBASE_PASSWORD
          value: "password"
        - name: LIQUIBASE_CHANGELOG
          value: "changelog/db.changelog-master.xml"
        command:
        - /bin/bash
        - -c
        - |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h postgres-service -p 5432 -U user; do
            echo "PostgreSQL is unavailable - sleeping"
            sleep 2
          done
          echo "PostgreSQL is ready - running migrations"
          liquibase --url="$LIQUIBASE_URL" \
                    --username="$LIQUIBASE_USERNAME" \
                    --password="$LIQUIBASE_PASSWORD" \
                    --changeLogFile="$LIQUIBASE_CHANGELOG" \
                    --searchPath=/liquibase/changelog \
                    update
        volumeMounts:
        - name: liquibase-changelog
          mountPath: /liquibase/changelog
      containers:
      - name: simple-bank
        image: ${DOCKER_IMAGE_NAME}
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: simple-bank-config
        - secretRef:
            name: simple-bank-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
      volumes:
      - name: liquibase-changelog
        configMap:
          name: liquibase-changelog
