apiVersion: v1
kind: ConfigMap
metadata:
  name: liquibase-changelog
  namespace: simple-bank
data:
  db.changelog-master.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <databaseChangeLog
            xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
                          http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.20.xsd">

        <include file="001-create-initial-schema.xml" relativeToChangelogFile="true"/>
        <include file="002-insert-sample-data.xml" relativeToChangelogFile="true"/>

    </databaseChangeLog>
  
  001-create-initial-schema.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <databaseChangeLog
            xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
                          http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.20.xsd">

        <changeSet id="1" author="system">
            <createTable tableName="customers">
                <column name="id" type="BIGSERIAL" autoIncrement="true">
                    <constraints primaryKey="true" nullable="false"/>
                </column>
                <column name="name" type="VARCHAR(255)"/>
                <column name="email" type="VARCHAR(255)"/>
                <column name="phone" type="VARCHAR(255)"/>
                <column name="customer_level" type="VARCHAR(255)"/>
            </createTable>

            <createTable tableName="accounts">
                <column name="id" type="BIGSERIAL" autoIncrement="true">
                    <constraints primaryKey="true" nullable="false"/>
                </column>
                <column name="balance" type="NUMERIC(38, 2)"/>
                <column name="account_type" type="VARCHAR(255)"/>
                <column name="cust_id" type="BIGINT"/>
            </createTable>

            <createTable tableName="transactions">
                <column name="id" type="BIGSERIAL" autoIncrement="true">
                    <constraints primaryKey="true" nullable="false"/>
                </column>
                <column name="value" type="NUMERIC(38, 2)"/>
                <column name="date" type="TIMESTAMP"/>
                <column name="description" type="VARCHAR(255)"/>
                <column name="type" type="VARCHAR(255)"/>
                <column name="from_account" type="BIGINT"/>
                <column name="to_account" type="BIGINT"/>
            </createTable>

            <addForeignKeyConstraint baseTableName="accounts"
                                     baseColumnNames="cust_id"
                                     constraintName="fk_account_customer"
                                     referencedTableName="customers"
                                     referencedColumnNames="id"/>
        </changeSet>

    </databaseChangeLog>
  
  002-insert-sample-data.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <databaseChangeLog
            xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
                          http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.20.xsd">

        <changeSet id="2" author="system" context="!test">
            <!-- Customer 1: Gold member -->
            <insert tableName="customers">
                <column name="id" value="1"/>
                <column name="name" value="John Doe"/>
                <column name="email" value="john.doe@example.com"/>
                <column name="phone" value="111-222-3333"/>
                <column name="customer_level" value="GOLD"/>
            </insert>
            <insert tableName="accounts">
                <column name="id" value="1"/>
                <column name="cust_id" value="1"/>
                <column name="account_type" value="SAVINGS"/>
                <column name="balance" value="15000.00"/>
            </insert>

            <!-- Customer 2: Silver member -->
            <insert tableName="customers">
                <column name="id" value="2"/>
                <column name="name" value="Jane Smith"/>
                <column name="email" value="jane.smith@example.com"/>
                <column name="phone" value="444-555-6666"/>
                <column name="customer_level" value="SILVER"/>
            </insert>
            <insert tableName="accounts">
                <column name="id" value="2"/>
                <column name="cust_id" value="2"/>
                <column name="account_type" value="CHECKING"/>
                <column name="balance" value="8500.00"/>
            </insert>

            <!-- Customer 3: Bronze member -->
            <insert tableName="customers">
                <column name="id" value="3"/>
                <column name="name" value="Sam Brown"/>
                <column name="email" value="sam.brown@example.com"/>
                <column name="phone" value="777-888-9999"/>
                <column name="customer_level" value="BRONZE"/>
            </insert>
            <insert tableName="accounts">
                <column name="id" value="3"/>
                <column name="cust_id" value="3"/>
                <column name="account_type" value="SAVINGS"/>
                <column name="balance" value="3200.00"/>
            </insert>
        </changeSet>

    </databaseChangeLog>
