apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-app
  namespace: simple-bank
spec:
  template:
    spec:
      containers:
      - name: simple-bank
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
